version: "3.3"
services:
  freeswitch:
    image: freeswitch:1.1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: freeswitch
    privileged: true
    network_mode: host
 
  
